# Generated by Django 5.0.2 on 2024-02-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AC',
            fields=[
                ('ACID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cmpID', models.IntegerField(primary_key=True, serialize=False)),
                ('cmpName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('typeID', models.IntegerField(primary_key=True, serialize=False)),
                ('typeStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('urgencyID', models.IntegerField(primary_key=True, serialize=False)),
                ('urgencyLevel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('AppID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('ACID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='project.ac')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DpID', models.IntegerField(primary_key=True, serialize=False)),
                ('DpName', models.CharField(max_length=20)),
                ('cmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='project.company')),
            ],
        ),
        migrations.AddField(
            model_name='ac',
            name='DpID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac', to='project.department'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('reqID', models.IntegerField(primary_key=True, serialize=False)),
                ('DpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purreq', to='project.department')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purreq', to='project.type')),
                ('urgencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purreq', to='project.urgency')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('purID', models.IntegerField(primary_key=True, serialize=False)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purit', to='project.item')),
                ('reqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purit', to='project.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='ApproverRequest',
            fields=[
                ('AppReq', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40)),
                ('ApproverDate', models.DateField()),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreq', to='project.approver')),
                ('reqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreq', to='project.purchaserequest')),
            ],
        ),
        migrations.AddField(
            model_name='ac',
            name='typeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac', to='project.type'),
        ),
        migrations.AddField(
            model_name='ac',
            name='urgencyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac', to='project.urgency'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('DpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='project.department')),
            ],
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purreq', to='project.user'),
        ),
        migrations.AddField(
            model_name='approver',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='project.user'),
        ),
    ]
